---
apiVersion: v2
name: nifi
version: 0.4.4
appVersion: 1.11.4
description: Apache NiFi is a software project from the Apache Software Foundation designed to automate the flow of data between software systems.
keywords:
  - nifi
  - data
  - process
home: https://nifi.apache.org/
icon: https://svn.apache.org/repos/asf/nifi/site/trunk/images/niFi-logo-horizontal-scaled.png
source:
  - https://github.com/cetic/helm-nifi
maintainers:
  - name: alexnuttinck
    email: alexandre.nuttinck@cetic.be
    url: https://github.com/alexnuttinck
dependencies:
  - name: zookeeper
    version: 2.1.1
    repository: https://kubernetes-charts-incubator.storage.googleapis.com/
    condition: zookeeper.enabled
